config/routes.rb
Twitter::Application.routes.draw do

  delete "posts/destroy"
  get "users/show"
  post "homepage/create"
  devise_for :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  get "homepage/home"
  root :to => "homepage#home"
  resources :relationships, only: [:create, :destroy]

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :user_id
  validates_presence_of :user_id
  validates_presence_of :content
  validates :content, :length => {:minimum =>1}
  belongs_to :user
  default_scope order('posts.created_at DESC')

  
  def self.from_users_followed_by(user)
    followed_user_ids = user.followed_user_ids
    where("user_id IN (?) OR user_id = ?", followed_user_ids, user)
  end

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id,:follower_id

  belongs_to :follower, class_name:"User"
  belongs_to :followed, class_name:"User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, :dependent => :destroy
  has_many :relationships, foreign_key: "follower_id", :dependent => :destroy
  has_many :followed_users, :through => :relationships, :source => :followed 
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", :dependent => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body



  def following?(other_user)
    self.relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    self.relationships.create!(followed_id: other_user.id)
  end  
  
  def unfollow!(other_user)
    self.relationships.find_by_followed_id(other_user.id).destroy
  end

  def feed
    Post.from_users_followed_by(self)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  before_filter :authenticate_user!
  def home
    #@home_posts = Post.all
    @followed_users = current_user.followed_users
    @followers = current_user.followers
    @feed = current_user.feed
  end

  def create
    post_text =  params['post_form']['new_post']
    @new_post=current_user.posts.create(:content=>post_text)
    redirect_to(homepage_home_path,notice:"new post has been created successfully")
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :is_authurized, :only => [:destroy,:update]
  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to(homepage_home_path,notice:"The post has been destroyed successfully")
  end
  

  def is_authurized
     if Post.find(params[:id]).user != current_user
       redirect_to(homepage_home_path,notice:"Sorry, you are not authorized to do this action")
     end
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @user = User.find(params[:relationship][:followed_id])
    current_user.follow!(@user)
    redirect_to @user
  end
  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow!(@user)
    redirect_to @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user_posts = User.find(params[:id]).posts
    @following = User.find(params[:id]).followed_users
    @followers = User.find(params[:id]).followers
    @user = User.find(params[:id])
  end

  def index
    @all_users = User.all
  end
  
  def following
    @following_users = User.find(params[:id]).followed_users
  end

  def followers
    @followers = User.find(params[:id]).followers
  end
  
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homepage/home.html.erb
<h1>Homepage#home</h1>
<p>Find me in app/views/homepage/home.html.erb</p>


<% if flash[:notice] %>
<div id="notice"><%= flash[:notice] %></div>
<% end %>


<H1>Welcome to our mini Twitter app <%=current_user.email%></h1>
<h3>Following: <%=link_to(@followed_users.count,following_user_path(current_user))%></h3>
<h3>Followers: <%=link_to(@followers.count,followers_user_path(current_user))%></h3>

<h3>Create new post </h3>
<%= form_tag :action => "create" do %>
    <%= text_area :post_form, :new_post, :cols => '40', :rows => '5' %>
    <%= submit_tag "Post" %>
<% end %>



<h3>Timeline</h3>
<table>

<% @feed.each do |post| %>
 <tr> <td><%= post.content %></td>
      <%if current_user.posts.include? post%>
      <td>&nbsp;<%=link_to("Delete",posts_destroy_path(:id =>post.id),:method=>:delete) %> </td> 
      <%end%>
 </tr>
<% end %>


</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Twitter</title>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
	<%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/homepage/home">Mini Twitter</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
		    <li>
                        <a href="/users">Users</a>
                    </li>
                    <li><% if user_signed_in? %>
                        <%= link_to "Profile", user_path(current_user) %>
                        <%else%>
                        <%= link_to "Profile", users_show_path %>
                        <%end%>
                    </li>
                    <li>
                        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        <% if notice%>
       <p class="alert alert-info"><%= notice %></p>
	<% end %>
	<% if alert %>
       <p class="alert alert-danger"><%= alert %></p>
	<% end %>
	<%= yield %>
    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id)) do |f| %>
<div><%= f.hidden_field :followed_id %></div>
<%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
html: { method: :delete }) do |f| %>
<%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/followers.html.erb
<h1>Users#followers</h1>
<p>Find me in app/views/users/index.html.erb</p>
<% if flash[:notice] %>
<div id="notice"><%= flash[:notice] %></div>
<% end %>

<table>
<% @followers.each do |user| %>
 <tr> <td><%= user.id %></td>
      <td>&nbsp;<%=link_to user.email,user_path(:id=>user.id) %> </td> 
 </tr>
<% end %>
</table>

app/views/users/following.html.erb
<h1>Users#following</h1>
<p>Find me in app/views/users/index.html.erb</p>
<% if flash[:notice] %>
<div id="notice"><%= flash[:notice] %></div>
<% end %>

<table>
<% @following_users.each do |user| %>
 <tr> <td><%= user.id %></td>
      <td>&nbsp;<%=link_to user.email,user_path(:id=>user.id) %> </td> 
 </tr>
<% end %>
</table>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<% if flash[:notice] %>
<div id="notice"><%= flash[:notice] %></div>
<% end %>

<table>
<% @all_users.each do |user| %>
 <tr> <td><%= user.id %></td>
      <td>&nbsp;<%=link_to user.email,user_path(:id=>user.id) %> </td> 
 </tr>
<% end %>
</table>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<% if flash[:notice] %>
<div id="notice"><%= flash[:notice] %></div>
<% end %>

<H1>Welcome to our mini Twitter app </h1>
<h3>Following: <%=link_to(@following.count,following_user_path)%></h3>
<h3>Followers: <%=link_to(@followers.count,followers_user_path)%></h3>


<% unless current_user == @user %>
<div id="follow_form">
<% if current_user.following?(@user) %>
<%= render 'unfollow' %>
<% else %>
<%= render 'follow' %>
<% end %>
</div>
<% end %>



<h3>User posts: </h3>

<table>
<% @user_posts.each do |post| %>
 <tr> <td><%= post.content %></td>
      <td>&nbsp;<%=link_to("Delete",posts_destroy_path(:id=>post.id),:method=>:delete) %> </td> 
 </tr>

<% end %>
</table>